name: Pouchers
description: A Financial Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.2.2
  firebase_messaging: ^14.4.1
  shared_preferences: ^2.0.13
  permission_handler: ^11.0.1
  flutter_dojah_kyc: ^0.3.3
  flutter_riverpod: ^2.0.2
  intercom_flutter: ^8.0.3
  pin_code_fields: ^8.0.1
  overlay_support: ^2.1.0
  firebase_core: ^2.10.0
  path_provider: ^2.0.9
  url_launcher: ^6.1.6
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.8
  share_plus: ^7.2.1
  local_auth: ^2.1.2
  printing: ^5.11.0
  riverpod: ^2.0.2
  lottie: ^2.7.0
  intl: ^0.18.1
  hive: ^2.2.3
  pdf: ^3.8.4

  hooks_riverpod: ^2.4.6

  flutter_native_contact_picker: ^0.0.6
  fast_contacts: ^3.0.3
  fluttercontactpicker: ^4.7.0

  # Util
  flutter_screenutil: ^5.9.0

  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # Environment
  flutter_dotenv: ^5.1.0

  # Service
  stacked_services: ^1.3.0
  stacked: ^3.4.1+1

  # Annotations
  riverpod_annotation: ^2.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  pull_to_refresh_flutter3: ^2.0.2

  community_charts_flutter: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.1
  collection: ^1.18.0
  flutter_inappwebview: ^6.0.0

  screenshot: ^2.1.0
  app_settings: ^5.1.1
  google_fonts: ^6.1.0
  local_auth_android: ^1.0.37
  local_auth_ios: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  stacked_generator: ^1.5.1
  custom_lint: ^0.5.6

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appicon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/background.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/background.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
    - .env.staging

  fonts:
    - family: Altone
      fonts:
        - asset: assets/fonts/altone-bold.ttf
        - asset: assets/fonts/altone-regular.ttf

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch
  lint: dart run custom_lint
  pod:
    - cd ios
    - pod repo update
    - pod update
  build_ipa:
    - flutter clean
    - flutter pub get
    - flutter build ipa --obfuscate --split-debug-info=build/symbols/
