name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: "3.19.6"
      - name: Create .env file if not exists
        run: |
          if [ ! -f .env ]; then
            echo "Create .env and .env.staging file" 
            touch .env,.env.staging
            echo "Writing contents to environment files"
            echo -e "${{ secrets.ENV }}" >> .env
            echo -e "${{ secrets.ENV_STAGING }}" >> .env.staging
            echo "Finished writing contents to environment files"
          else
            echo "environment file already exists, skipping creation"
          fi
      - name: Create google-services.json file if not exists
        run: |
          echo "Navigating into android app module"
          cd android/app
          if [ ! -f google-services.json ]; then
            echo "Create google-services.json file"
            touch google-services.json
            echo "Writing contents to google-services.json file"
            echo -e "${{ secrets.GOOGLE_SERVICE }}" >> google-services.json
            echo "Finished writing contents to google-services.json file"
          else
            echo "google-services.json file already exists, skipping creation"
          fi
          echo "Exiting android app module"
          cd ../..
      - run: flutter clean
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.P_TOKEN }}
