name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: "3.19.6"
      - name: Create .env file if not exists
        run: |
          if [ ! -f .env ]; then
            echo "Create .env file"
            touch .env .env.staging
            echo "Writing contents to .env file"
            echo -e "APP_NAME=${{ secrets.APP_NAME }}\n\
            API_URL=${{ secrets.API_URL }}\n\
            TERMS_OF_USE=${{ secrets.TERMS_OF_USE }}\n\
            PRIVACY_POLICY=${{ secrets.PRIVACY_POLICY }}\n\
            INTERCOM_ANDROID_KEY=${{ secrets.INTERCOM_ANDROID_KEY }}\n\
            INTERCOM_APP_ID=${{ secrets.INTERCOM_APP_ID }}\n\
            INTERCOM_IOS_KEY=${{ secrets.INTERCOM_IOS_KEY }}\n\
            DOJAH_PUBLIC_KEY=${{ secrets.DOJAH_PUBLIC_KEY }}\n\
            DOJAH_APP_ID=${{ secrets.DOJAH_APP_ID }}\n\
            DOJAH_DRIVER_LICENSE_KEY=${{ secrets.DOJAH_DRIVER_LICENSE_KEY }}\n\
            DOJAH_VOTERS_CARD_KEY=${{ secrets.DOJAH_VOTERS_CARD_KEY }}\n\
            DOJAH_INTERNATIONAL_PASSPORT_KEY=${{ secrets.DOJAH_INTERNATIONAL_PASSPORT_KEY }}\n\
            DOJAH_VNIN_KEY=${{ secrets.DOJAH_VNIN_KEY }}\n\
            DOJAH_NIN_KEY=${{ secrets.DOJAH_NIN_KEY }}\n\
            VGS_API_URL=${{ secrets.VGS_API_URL }}" >> .env
            echo "Finished writing contents to .env file"
            cat .env
          else
            echo ".env file already exists, skipping creation"
          fi
      - name: Create google-service.json file if not exists
        run: |
          echo "Navigating into android app module"
          cd android/app
          if [ ! -f google-service.json ]; then
            echo "Create google-service.json file"
            touch google-service.json
            echo "Writing contents to google-service.json file"
            echo -e "${{ secrets.GOOGLE_SERVICE }}" >> google-service.json
            echo "Finished writing contents to google-service.json file"
            cat google-service.json
          else
            echo "google-service.json file already exists, skipping creation"
          fi
          echo "Exiting android app module"
          cd ../..
      - run: flutter clean
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.P_TOKEN }}
